<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1845532112940262"
     crossorigin="anonymous"></script>
<!-- 文章底部广告位 -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-1845532112940262"
     data-ad-slot="7283746572"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>